# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  instance_count = ENV["VG_COUNT"] || 3
  instance_username = ENV["VG_USERNAME"] || "ci"
  public_key_file = ENV["VG_PUBLIC_KEY_FILE"] || "#{Dir.home}/.ssh/id_rsa.pub"

  (1..instance_count).each do |id|
    instance_name = "ci-instance-#{id}"
    
    # define a scope for each instance
    config.vm.define instance_name do |ins|
      ins.vm.box = "hashicorp/bionic64"
      ins.vm.hostname = instance_name
      ins.vm.network "private_network", ip: "192.168.20.#{20+id}"

      ins.vm.provider "virtualbox" do |vb|
        vb.name = instance_name
        vb.memory = 1024
        vb.cpus = 1
      end

      ins.vm.provision "shell" do |s|
        public_key_content = File.readlines(public_key_file).first.strip
        s.inline = <<-SHELL
          # ci user
          useradd -s /bin/bash -d /home/#{instance_username}/ -m -G sudo #{instance_username}
          echo #{instance_username} 'ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          mkdir -p /home/#{instance_username}/.ssh && chown -R #{instance_username} /home/#{instance_username}/.ssh
          echo #{public_key_content} >> /home/#{instance_username}/.ssh/authorized_keys
        SHELL
      end

    end

  end

end