version: "3.6"

services:

  gitlab-runner-1:
    image: "gitlab/gitlab-runner:alpine3.13-v14.8.3"
    container_name: gitlab-runner-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      gitlabrunnernetwork:
        ipv4_address: 172.22.0.15

  gitlab-runner-2:
    container_name: gitlab-runner-2
    image: "gitlab/gitlab-runner:alpine3.13-v14.8.3"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      gitlabrunnernetwork:
        ipv4_address: 172.22.0.16

networks:
  gitlabrunnernetwork:
    name: gitlab-runner-network
    ipam:
      config:
        - subnet: 172.22.0.0/16
